config/routes.rb
Rails.application.routes.draw do
  get 'articulos/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "articulos#index"

  resources :articulos do
    resources :comentarios, only: [:create, :update, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articulo.rb
class Articulo < ApplicationRecord
    has_many :comentarios, dependent: :destroy

    validates :titulo, presence: true
    validates :descripcion, presence: true, length: { minimum: 10 }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
    belongs_to :articulo

    validates :titulo, presence: true
    validates :cuerpo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  
  protect_from_forgery with: :null_session

  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  def index
    @articulos = Articulo.all
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def new
    @articulo = Articulo.new
  end

  def create
    @articulo = Articulo.new(articulo_params)

    if @articulo.save
      redirect_to @articulo, notice: "Artículo creado con éxito "
      
    else
      render :new, status: :unprocessable_entity
      
    end
  end

  def edit
    @articulo = Articulo.find(params[:id])
  end

  def update
    @articulo = Articulo.find(params[:id])

    if @articulo.update(articulo_params)
      redirect_to @articulo
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy

    redirect_to root_path, status: :see_other
  end

  def set_articulo
    @articulo = Articulo.find(params[:id])
  end

  private

  def articulo_params
    params.require(:articulo).permit(:titulo, :descripcion)
  end

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    def create
        @articulo = Articulo.find(params[:articulo_id])
        @comentario = @articulo.comentarios.create(comentario_params)
        redirect_to articulo_path(@articulo)
      end

    def destroy
        @articulo = Articulo.find(params[:articulo_id])
        @comentario = @articulo.comentarios.find(params[:id])
        @comentario.destroy
        redirect_to articulo_path(@articulo), status: :see_other
    end
    
      private
        def comentario_params
          params.require(:comentario).permit(:titulo, :cuerpo)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_with model: articulo do |form| %>
    <div>
      <%= form.label :Título %><br>
      <%= form.text_field :titulo %>
      <% articulo.errors.full_messages_for(:titulo).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :Descripción %><br>
      <%= form.text_area :descripcion %><br>
      <% articulo.errors.full_messages_for(:descripcion).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/articulos/edit.html.erb
<h1>Editar Artículo</h1>

<%= render "form", articulo: @articulo %>

app/views/articulos/index.html.erb
<h1>Articulos</h1>
<ul>
  <% @articulos.each do |articulo| %>
    <li><%= link_to articulo.titulo, articulo %></li>
  <% end %>
</ul>
<%= link_to 'Nuevo Articulo', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>Nuevo Artículo</h1>

<%= render "form", articulo: @articulo %>

app/views/articulos/show.html.erb
<h1><%= @articulo.titulo %></h1>

<p><%= @articulo.descripcion %></p>

<ul>
    <li><%= link_to 'Editar', edit_articulo_path(@articulo) %></li>
    <li>
        <%= link_to 'Eliminar', articulo_path(@articulo),
                    data: { 
                    turbo_method: :delete,
                    turbo_confirm: '¿Estás seguro?' } %>
    </li>
    <li><%= link_to 'Volver', root_path %></li>
<ul>

<h2>Comentarios:</h2>
<%= render @articulo.comentarios %>

<h2>Agrege un comentario:</h2>
<%= render 'comentarios/form' %>

app/views/comentarios/_comentario.html.erb
<p>
    <strong>Titulo:</strong>
    <%= comentario.titulo %>
</p>
<p>
    <strong>Comentario:</strong>
    <%= comentario.cuerpo %>
</p>
<p>
    <%= link_to "Eliminar", [comentario.articulo, comentario],
                data: { 
                    turbo_method: :delete,
                    turbo_confirm: "¿Estás seguro?"} %>
</p>

app/views/comentarios/_form.html.erb
<%= form_with model: [ @articulo, @articulo.comentarios.build ] do |form| %>
    <p>
      <%= form.label :Título %><br>
      <%= form.text_field :titulo %>
    </p>
    <p>
      <%= form.label :Comentario %><br>
      <%= form.text_area :cuerpo %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>